### ISSUE TITLE
Osmium is out of service

### ISSUE THREAD

**Issue by SkuliAdams** [ayust/alpha-guide#21]
As osmium is out of service, something new is needed to show ship fittings.

**Comment by sweeney-7bb** [comment]
we could just put text blocks directly on the page properly formatted to be copied-imported, right? I've already got all the fits made and saved in the game, so i could export them

**Comment by ayust** [comment]
Yes, we could definitely do that, and it's probably the most future-proof option. We had originally gone with Osmium since it provided the nice visual display, but given the simulation view now available in-game, providing just the importable fit is probably sufficient.

If you could export them all that would be excellent! I didn't actually have a plaintext version of the fits saved so that will save a lot of time relative to reconstructing them from the descriptions on each page.

It'd be most helpful if you were able to send a pull request replacing the osmium object on each page with corresponding plaintext fits, but I'll take even just a bunch of fit dumps - it'll just take a bit longer if I have to go through and update the pages, since my time is stretched a bit thin right now.

**Comment by sweeney-7bb** [comment]
I understand the stretched time bit, I'll do it per link since that'll be easier on you. I'm new to this bit, but the pull request, is that what the edit page / creating a fork does?

**Comment by ayust** [comment]
Yep, the "Edit this file" button (pencil icon, e.g. on [an individual file page) is the easiest way for someone new to Git / GitHub to propose a single change. If you want to propose a bunch of changes, you may want to check out the entire repository to work on, but I'm also fine with accepting just a lot of small pull requests. :)

**Comment by sweeney-7bb** [comment]
as a test i submitted the change for the Amarr Impairor. let me know if there's anything i need do differently with formatting, etc

**Comment by ayust** [comment]
So it looks like you committed the change to a branch in your copy, but didn't submit it as a pull request. To do that, [click here](https://github.com/ayust/alpha-guide/compare/master...sweeney-7bb:patch-1) and then look for the big green button.

**Comment by sweeney-7bb** [comment]
ahh, ok. done

**Comment by ayust** [comment]
Thanks for your efforts so far on this @sweeney-7bb

**Comment by sweeney-7bb** [comment]
no problem! i'm happy to be able to help :)

**Comment by sweeney-7bb** [comment]
whew! changes for all ship fits submitted. most have already been merged :)

**Comment by ayust** [comment]
Thank you very much, @sweeney-7bb !
